export const ar = {
    lang: 'English',
    home: 'الرئيسية',
    myOrders: 'طلباتي',
    changeInfo: 'تغير البيانات',
    changePwp: 'تغير كلمة المرور',
    newAccount: 'انشاء حساب جديد',
    login: 'تسجيل الدخول',
    currency: 'العملة',
    search: 'جار البحث',
    favourite: 'المفضلة',
    selectCurrency: 'اختر العملة',
    languages: 'اللغة',
    categories: 'الفئات',
    about: 'عنا',
    aboutPage: 'عنا',
    terms: 'الشروط و الاحكام',
    policy: 'سياسة الشحن و التوصيل', 
    info: 'معلومات الدفع',
    service: 'خدماتي',
    copy: 'الاجواد © جميع الحقوق محفوظه.',
    newest: 'احدث المنتجات',
    offers: 'العروض',
    bestSeller: 'الاكثر مبيعا',
    addToCart: 'أضف الى السلة',
    addedToCart: 'تمت الاضافة الى السلة',
    categoryPagination: 'جار تحميل المزيد من المتاجر ...',
    categoryPaginationNotFound: 'لا توجد المزيد من المتاجر',
    noCategoryProduct: 'لا توجد متاجر لهذه الفئة',
    cart: 'سلة المشتريات',
    cartItemImage: 'الصورة',
    cartItem: 'المنتج',
    cartItemquantity: 'الكمية',
    cartItemPrice: 'السعر',
    cartTotal: 'الاجمالي',
    cartCheckOut: 'اتمام العملية',
    noCart: 'لا توجد منتجات في عربة التسوق',
    proPageName: 'الاسم',
    proPageSize: 'الحجم',
    proPageQuantity: 'الكمية',
    proPagePrice: 'السعر',
    proRivew: 'تقيم العملاء',
    noProRivew: 'لا توجد تقيمات لهاذا المنتج',
    proRelated: 'منتجات ذات صلة',
    noProRelated: 'لا توجد منتجات ذات صلة',
    noPro: 'لا توجد منتجات',
    loginUsername: 'اسم المستخدم',
    loginPwp: 'كلمة المرور',
    loginBtn: 'تسجيل الدخول',
    emailPlaceholder: 'البريد الالكتروني',
    pwpBackBtn: 'استعادة كلمة المرور',
    forgetPwp: 'هل نسيت كلمة المرور؟',
    askLogin: 'هل تود تسجيل الدخول؟',
    mobilePlaceholder: 'رقم الهاتف', 
    regBtn: 'انشاء حساب جديد',
    regTitle: 'انشاء حساب جديد',
    regTermsAgree: 'الموافقة على الشروط و الاحكام', 
    newEmailPlaceHolder: 'البريد الالكتروني الجديد',
    newMobilePlaceHolder: 'رقم الهاتف الجديد',
    changeInfoBtn: 'تغير البيانات',
    changeInfoTitle: 'تغيير بيانات حسابك',
    changePwpTitle: 'تغيير كلمة المرور',
    changePwpExisting: 'كلمة المرور الحالية',
    changePwpNew: 'كلمة المرور الجديدة',
    changePwpRe: 'اعادة كتابة كلمة المرور الجديدة',
    changePwpBtn: 'تغيير كلمة المرور',
    myOrdersTitle: 'طلباتي',
    myOrdersReady: 'قيد المراجعة',
    myOrdersOnRoad: 'قيد الشحن',
    myOrdersDone: 'جاري الشحن',
    myOrdersDelivred: 'تم التوصيل',
    OrderNumber: 'رقم الطلبية',
    OrderStatus: 'حالة الطلب',
    OrderDate: 'تاريخ الطلب',
    OrderTotal: 'المجموع',
    orderProImage: 'صورة المنتج',
    orderProName: 'اسم المنتج',
    orderProQuantity: 'الكمية',
    orderProPrice: 'السعر',
    orderProTotal: 'الاجمالي',
    orderProReview: 'قيم المنتج',
    proRateLable: 'قيم المنتج',
    proRateCommint: 'اكتب تعليقا',
    proRateAdd: 'اضافة تقييم',
    newAccountFromLogin: 'ليس لديك حساب؟ سجل الان',
    CompletePayment: 'اتمام العملية',
    PaymentOrder: 'ملخص الطلبات',
    orderTotal: 'الاجمالي',
    orderShipping: 'تكلفة الشحن',
    totalOrder: 'التكلفة الاجمالية',
    shippingInfo: 'معلومات التوصيل',
    paymentMethod: 'طريقة الدفع',
    creditCard: 'بطاقة الاتمان',
    bankTransfer: 'التحويل البنكي',
    bankName: 'اسم البنك',
    accountName: 'اسم الحساب',
    acountNumber: 'رقم الحساب',
    comment: 'ملاحظة',
    bankNameFixed: 'جويد',
    accountNameFixed: 'جويد',
    acountNumberFixed: '07727402693',
    commentFixed: 'لن يتم اعتماد الطلب بشكل نهائي حتى يتم تحويل المبلغ عبر الحساب و ارسال صورة من ايصال التحويل ورقم الطلب على الواتس اب او البريد الالكتروني',
    addRequest: 'اعتماد الطلب',
    storProductLoader: 'جار تحميل المزيد من المنتجات ...',
    storProductNoProducts: 'لا توجد المزيد من المنتجات',
    storProductNotFound: 'لا توجد منتجات في هذا المتجر',
    aboutPageTitle: 'من نحن', 
    paymentPageTitle: 'معلومات الدفع',
    shippingPageTitle: 'سياسة الشحن و التوصيل',
    termsPageTitle: 'الشروط و الاحكام'
}

export const en = {
    lang: 'العربية',
    home: 'Home',
    myOrders: 'My Orders',
    changeInfo: 'Change my Information',
    changePwp: 'Change Password',
    newAccount: 'New Account',
    login: 'Login',
    currency: 'Currency',
    search: 'Searching',
    favourite: 'My Favourites',
    selectCurrency: 'Select currency',
    languages: 'Language',
    categories: 'Categories',
    about: 'About',
    aboutPage: 'About us',
    terms: 'Terms & Conditions',
    policy: 'Shipping & Policy', 
    info: 'Payment Information',
    service: 'My Services',
    copy: 'All Rights Reserved © Alajwad.',
    newest: 'Newest',
    offers: 'Offers',
    bestSeller: 'Best Seller',
    addToCart: 'Add to Cart',
    addedToCart: 'Added to Cart',
    categoryPagination: 'Loading More Stors ...',
    categoryPaginationNotFound: 'No More Stors',
    noCategoryProduct: 'No Stors at this Category',
    cart: 'Cart Items',
    cartItemImage: 'Image',
    cartItem: 'Item',
    cartItemquantity: 'Quantity',
    cartItemPrice: 'Price',
    cartTotal: 'Total',
    cartCheckOut: 'Proceed',
    noCart: 'No Items on the Cart',
    proPageName: 'Name',
    proPageSize: 'Size',
    proPageQuantity: 'Quantity',
    proPagePrice: 'Price',
    proRivew: 'Customer Reviews',
    noProRivew: 'No Reviews for this Product',
    proRelated: 'Related Products',
    noProRelated: 'No Related Products',
    noPro: 'No Products',
    loginUsername: 'Username',
    loginPwp: 'Password',
    loginBtn: 'Login',
    emailPlaceholder: 'Email address',
    pwpBackBtn: 'Get your Password',
    forgetPwp: 'Forget Password?',
    askLogin: 'Want to Login?',
    mobilePlaceholder: 'Mobile Number',
    regBtn: 'Create New Account',
    regTitle: 'Create New Account',
    regTermsAgree: 'Agree to the Terms and Conditions',
    newEmailPlaceHolder: 'New Email Address',
    newMobilePlaceHolder: 'New Phone Number',
    changeInfoBtn: 'Change Your Information',
    changeInfoTitle: 'Change your Information',
    changePwpTitle: 'Change your Password',
    changePwpExisting: 'Current Password',
    changePwpNew: 'New Password',
    changePwpRe: 'Retype your New Password',
    changePwpBtn: 'Change your Password',
    myOrdersTitle: 'My Orders',
    myOrdersReady: 'In Review',
    myOrdersOnRoad: 'In Shipping',
    myOrdersDone: 'In Road',
    myOrdersDelivred: 'Delivred',
    OrderNumber: 'Order Number',
    OrderStatus: 'Order Status',
    OrderDate: 'Order Date',
    OrderTotal: 'Total',
    orderProImage: 'Product Image',
    orderProName: 'Product Name',
    orderProQuantity: 'Quantity',
    orderProPrice: 'Price',
    orderProTotal: 'Total',
    orderProReview: 'Rate the Product',
    proRateLable: 'Rate the Product',
    proRateCommint: 'Add Comment',
    proRateAdd: 'Rate Now',
    newAccountFromLogin: "Don't have an account? Register Now!",
    CompletePayment: 'Complete Payment',
    PaymentOrder: 'Order',
    orderTotal: 'Total',
    orderShipping: 'Shipping',
    totalOrder: 'Total Order',
    shippingInfo: 'Your Shipping Info',
    paymentMethod: 'Payment Method',
    creditCard: 'Credit Card',
    bankTransfer: 'Bank Transfer',
    bankName: 'Bank Name',
    accountName: 'Account Name',
    acountNumber: 'Acount Number',
    comment: 'Comment',
    bankNameFixed: 'Jawid',
    accountNameFixed: 'Jawid',
    acountNumberFixed: '07727402693',
    commentFixed: 'The request will not be permanently approved until the amount is transferred via the account and a copy of the transfer receipt and order number is sent to WhatsApp or e-mail.',
    addRequest: 'Confirm Now',
    storProductLoader: 'Loading More Products ...',
    storProductNoProducts: 'No More Products',
    storProductNotFound: 'No Products at this Store',
    aboutPageTitle: 'About us',
    paymentPageTitle: 'Payment Information',
    shippingPageTitle: 'Shipping and Delivery',
    termsPageTitle: 'Terms and Conditions'
}

export function getLang() {
    return localStorage.getItem('lang');
}